apiVersion: v1
kind: Service
metadata:
  name: svc-customer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30201
  selector:
    app: customer-service
